/* tools/answer-key.js — regenerates ANSWER_KEY.md from the bank.
 *
 *   node tools/answer-key.js > ANSWER_KEY.md
 *
 * Everything here is derived, so the key cannot drift from what students see.
 * The loss column is computed as M − m/z, exactly the way Level 1 keys it.
 */
const fs = require('fs');
const path = require('path');

const src = path.join(__dirname, '..', 'src', 'js');
eval(fs.readFileSync(path.join(src, 'fragments.js'), 'utf8'));
eval(fs.readFileSync(path.join(src, 'compounds.js'), 'utf8'));
global.getComputedStyle = () => ({ getPropertyValue: () => '' });
eval(fs.readFileSync(path.join(src, 'massspec.js'), 'utf8'));

const out = [];
const w = s => out.push(s);

const MECH = {
  alpha: 'α-cleavage', branch: 'branch point', benzylic: 'benzylic',
  dehydr: 'dehydration', sigma: 'σ C–C'
};

const ROLE = {
  mplus:   'molecular ion — **scored**',
  key:     '**scored**',
  cluster: 'drawn; above the line but not diagnostic',
  minor:   'drawn; below the reading line',
  mcl:     'drawn; McLafferty rearrangement — never scored'
};

w('# Answer key — Mass Spectrometry: Reading the Fragments');
w('');
w('Generated by `tools/answer-key.js`. Do not edit by hand — edit');
w('`src/js/compounds.js` and regenerate.');
w('');
w('Relative intensities are rounded and idealised, and the renderer wobbles them a');
w('few percent on every draw, so a student never sees exactly the numbers below.');
w('Peak *positions* are exact. Isotope peaks are not listed: `massspec.js` computes');
w('M+1 and M+2 from the molecular formula at draw time, so they are always right.');
w('');
w('**Scored** peaks are the ones a student is asked to label. Everything else is');
w('drawn to make the spectrum honest, and explains itself when clicked.');
w('');

/* ------------------------------------------------------------ the compounds */

const byTheme = {};
for (const c of COMPOUNDS) (byTheme[c.theme] = byTheme[c.theme] || []).push(c);

const THEME_NAME = {
  alcohol:  'Alcohols — α-cleavage and dehydration',
  carbonyl: 'Carbonyls — the acylium',
  arene:    'Arenes — benzylic cleavage and tropylium',
  branch:   'Chains — the tertiary carbocation',
  hetero:   'Amines and ethers — α-cleavage again',
  halide:   'Halides — isotope patterns'
};

for (const theme of Object.keys(THEME_NAME)) {
  w('## ' + THEME_NAME[theme]);
  w('');
  for (const c of byTheme[theme] || []) {
    const M = MS.massOf(MS.parseFormula(c.f));
    const base = c.peaks.find(p => p.ab === 100);
    w('### ' + c.name + '  ·  `' + c.id + '`');
    w('');
    w('| | |');
    w('| --- | --- |');
    w('| Formula | ' + c.formula + ' |');
    /* "absent" and "present but unreadable" are different lessons, and the
       bank distinguishes them: a compound whose M+ is real but ~1% carries a
       `minor` peak at M, while one that never survives has no peak there. */
    const atM = c.peaks.find(p => p.mz === M);
    w('| Molecular ion | **' + M + '**' +
      (atM && atM.role === 'mplus' ? '  — ' + atM.ab + '%, scored'
       : atM ? '  — *only ' + atM.ab + '%: drawn, but too weak to measure a loss from, so this ' +
               'compound is kept out of Level 1*'
       : '  — *not observed at all; the molecule falls apart on ionisation*') + ' |');
    w('| Base peak | **m/z ' + base.mz + '**' +
      (base.ion && IONS[base.ion] ? '  ' + IONS[base.ion].label + ', ' + IONS[base.ion].name : '') +
      ' |');
    w('| Class | ' + c.cls + ' |');
    w('| Levels | ' + c.tags.join(', ') + ' |');
    w('');
    w('| m/z | % | Loss | Ion | Mechanism | Role |');
    w('| ---: | ---: | --- | --- | --- | --- |');
    for (const p of c.peaks.slice().sort((a, b) => b.mz - a.mz)) {
      const ion = p.ion ? IONS[p.ion] : null;
      /* The loss view is how Level 1 keys a peak, and it is only offered for
         peaks Level 1 actually asks about. Printing "−33" against a cluster
         peak would invite reading a neutral loss that nobody proposes. */
      const loss = M - p.mz;
      const lossText = (p.role !== 'key' || !LOSSES[loss]) ? '—'
        : '−' + loss + ' (' + LOSSES[loss].neutral +
          (LOSSES[loss].also ? ' / ' + LOSSES[loss].also : '') + ')';
      w('| ' + p.mz + ' | ' + p.ab + ' | ' + lossText + ' | ' +
        (ion ? ion.label + ' ' + (ion.f ? '`' + ion.f + '`' : '') : '—') + ' | ' +
        (ion ? (MECH[ion.mech] || ion.mech) : '—') + ' | ' + (ROLE[p.role] || p.role) + ' |');
    }
    w('');
    const keys = c.peaks.filter(p => p.role === 'key');
    if (keys.length) {
      w('**Why each scored peak is where it is**');
      w('');
      for (const p of keys.slice().sort((a, b) => b.ab - a.ab)) {
        w('- **m/z ' + p.mz + '** (' + p.ab + '%) — ' + p.why);
      }
      w('');
    }
    const notes = c.peaks.filter(p => p.note);
    if (notes.length) {
      w('**Peaks that need a caveat in class**');
      w('');
      for (const p of notes) w('- **m/z ' + p.mz + '** — ' + p.note);
      w('');
    }
    if (c.peaks.some(p => p.role === 'mcl')) {
      const m = c.peaks.find(p => p.role === 'mcl');
      w('> **m/z ' + m.mz + ' is a McLafferty rearrangement peak.** It is drawn because it is' +
        ' really there, but it can never be scored, and clicking it tells the student it comes' +
        ' from a rearrangement this unit does not cover.');
      w('');
    }
  }
}

/* --------------------------------------------------------- the vocabularies */

w('## Common losses');
w('');
w('| Loss | Neutral | What it means |');
w('| ---: | --- | --- |');
for (const n of Object.keys(LOSSES).map(Number).sort((a, b) => a - b)) {
  const L = LOSSES[n];
  w('| −' + n + ' | ' + L.neutral + (L.also ? '  **or**  ' + L.also : '') + ' | ' + L.hint + ' |');
}
w('');

w('## Ions worth knowing on sight');
w('');
w('| m/z | Ion | Formula | Stability | Why |');
w('| ---: | --- | --- | --- | --- |');
for (const k of ION_IDS.filter(k => IONS[k].mz).sort((a, b) => IONS[a].mz - IONS[b].mz)) {
  const g = IONS[k];
  w('| ' + g.mz + ' | ' + g.label + ' — ' + g.name + ' | `' + g.f + '` | ' + g.cls + ' | ' +
    g.hint + ' |');
}
w('');

/* Ions that share an m/z are the whole point of Level 2. */
const byMz = {};
for (const k of ION_IDS) if (IONS[k].mz) (byMz[IONS[k].mz] = byMz[IONS[k].mz] || []).push(k);
const twins = Object.keys(byMz).filter(mz => byMz[mz].length > 1);
if (twins.length) {
  w('## The ambiguous masses');
  w('');
  w('These are the masses where the arithmetic alone will not settle it, and the rest of');
  w('the spectrum has to. Level 2 offers one against the other on purpose.');
  w('');
  w('| m/z | Candidates | Settled by |');
  w('| ---: | --- | --- |');
  for (const mz of twins.sort((a, b) => a - b)) {
    const ks = byMz[mz];
    /* What actually separates two ions of the same mass is derived, not
       asserted: either their formulas differ in oxygen — in which case
       looking for a C=O or an O–H settles it — or the formulas are
       identical, and nothing about the mass can settle it at all. */
    const forms = ks.map(k => IONS[k].f);
    const oxy = ks.map(k => (MS.parseFormula(IONS[k].f).O || 0));
    const sameFormula = forms.every(f => f === forms[0]);
    const settled = sameFormula
      ? '**nothing at this mass can** — identical formulas. Only the rest of the ' +
        'pattern, and the structures on offer, decide it.'
      : oxy.some(n => n === 0) && oxy.some(n => n > 0)
        ? 'whether the molecule contains oxygen at all: only ' +
          ks.filter((k, i) => oxy[i] > 0).map(k => IONS[k].label).join(' / ') +
          ' needs a C=O or an O–H.'
        : 'how many oxygens: ' + ks.map((k, i) => IONS[k].label + ' has ' + oxy[i]).join(', ') + '.';
    w('| ' + mz + ' | ' + ks.map(k => IONS[k].label + ' (' + IONS[k].name + ')').join('  **vs**  ') +
      ' | ' + settled + ' |');
  }
  w('');
}

/* ------------------------------------------------------- identify questions */

const SIG = {};
for (const c of COMPOUNDS) {
  SIG[c.id] = c.peaks.filter(p => p.role === 'key' || p.role === 'mplus')
                     .map(p => p.mz).sort((a, b) => a - b).join(',');
}
const clusters = {};
for (const id of Object.keys(SIG)) (clusters[SIG[id]] = clusters[SIG[id]] || []).push(id);
const collisions = Object.values(clusters).filter(g => g.length > 1);

w('## Compounds that cannot be told apart here');
w('');
if (!collisions.length) {
  w('None — every compound has a distinct set of scored peaks.');
} else {
  w('These share a scored-peak set, so a student has no way to choose between them from');
  w('the evidence this activity gives. The identify question never offers one against');
  w('another; they simply turn up in different items.');
  w('');
  for (const g of collisions) {
    w('- ' + g.map(id => COMPOUNDS.find(c => c.id === id).name).join(' **vs** ') +
      '  — both show m/z ' + SIG[g[0]].split(',').join(', '));
  }
}
w('');

w('## Level 3: the predictions');
w('');
w('Each of these compounds offers two or more competing cleavages. The student picks the');
w('one giving the most stable cation, then works out its m/z.');
w('');
for (const c of COMPOUNDS.filter(c => c.tags.includes('predict'))) {
  const M = MS.massOf(MS.parseFormula(c.f));
  const routes = c.peaks.filter(p => p.role === 'key' && p.ion && IONS[p.ion]);
  w('- **' + c.name + '** (M = ' + M + ') → ' +
    routes.slice().sort((a, b) => b.ab - a.ab)
      .map(p => IONS[p.ion].label + ' at ' + p.mz + (p.ab === 100 ? ' **(wins)**' : ''))
      .join('  ·  '));
}
w('');

console.log(out.join('\n'));
