/* tools/answer-key.js — regenerates ANSWER_KEY.md from the content files.
 *
 *   node tools/answer-key.js > ANSWER_KEY.md
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const src = path.join(__dirname, '..', 'src', 'js');
for (const f of ['data.js', 'chem.js', 'cfu.js', 'plan.js']) {
  vm.runInThisContext(fs.readFileSync(path.join(src, f), 'utf8'), { filename: f });
}

const U = Chem.uni;
const out = [];
const p = (s = '') => out.push(s);

p('# Answer key — Naming Ionic Compounds');
p();
p('Generated by `node tools/answer-key.js > ANSWER_KEY.md`. Do not edit by hand.');
p();
p('## The rule');
p();
p('**IF** the positive ion is a transition metal → metal (Roman numeral) + negative ion.');
p('**OTHERWISE** → positive ion + negative ion.');
p();
p('Transition metals in this class: ' + DATA.CATIONS.filter((c) => c.tm).map((c) => c.t).join(', ') +
  '. Ag and Zn are **not** transition metals (Ag⁺ and Zn²⁺ only).');
p('Mercury is used only as Hg²⁺; mercury(I), Hg₂²⁺, is left out.');
p();

p('## Positive ions');
p();
p('| Ion | Name | Charge(s) | Roman numeral? |');
p('| --- | --- | --- | --- |');
for (const c of DATA.CATIONS) {
  p('| ' + U(c.t) + ' | ' + c.name + ' | ' + c.charges.map((q) => q + '+').join(', ') + ' | ' +
    (c.tm ? 'yes' : 'no') + ' |');
}
p();

p('## Negative ions');
p();
p('| Ion | Name | Kind |');
p('| --- | --- | --- |');
for (const a of DATA.ANIONS) {
  p('| ' + Chem.anIon(a) + (a.alt ? ' (also ' + U(a.alt) + '⁻)' : '') + ' | ' + a.name + ' | ' +
    (a.poly ? 'polyatomic' : 'from ' + a.el) + ' |');
}
p();

p('## Pairings left out');
p();
p('- Peroxide (O₂²⁻) is paired only with Group 1 and Group 2 metals (not Be). With a transition');
p('  metal its formula collides with an oxide: lead(II) peroxide and lead(IV) oxide would both be PbO₂.');
p('- Ammonium is never paired with nitride, phosphide, oxide or peroxide.');
p('- Chromium is never paired with chromate or dichromate, nor manganese with permanganate.');
p();

const all = Chem.all();
p('## Every compound in the pool (' + all.length + ')');
p();
for (const c of DATA.CATIONS) {
  const list = all.filter((x) => x.c === c);
  if (!list.length) continue;
  p('### ' + c.name + ' (' + U(c.t) + ')');
  p();
  p('| Formula | Name |');
  p('| --- | --- |');
  for (const cpd of list) {
    p('| ' + U(Chem.formula(cpd)) + (cpd.a.alt ? ' or ' + U(Chem.formula(cpd, true)) : '') + ' | ' +
      Chem.name(cpd) + ' |');
  }
  p();
}

p('## Check-for-understanding bank (' + CFU.BANK.length + ' written questions)');
p();
p('Generated questions (metal charge from a formula, pick the formula, pick the name) are built from');
p('the compound pool above and are not listed.');
p();
p('| Id | First level | Question | Answer | Why |');
p('| --- | --- | --- | --- | --- |');
const esc = (s) => s.replace(/\|/g, '\\|');
for (const b of CFU.BANK) {
  p('| ' + b.id + ' | ' + b.min + ' | ' + esc(b.q) + ' | ' + esc(b.a[0]) + ' | ' + esc(b.why) + ' |');
}

process.stdout.write(out.join('\n') + '\n');
