/* tools/answer-key.js — regenerates ANSWER_KEY.md from the bank.
 *
 *   node tools/answer-key.js > ANSWER_KEY.md
 *
 * Everything in the key is read from compounds.js, groups.js and
 * fragments.js, or worked out by evidence.js, so it cannot drift from what
 * the activity actually asks.
 */
const fs = require('fs');
const path = require('path');

const src = path.join(__dirname, '..', 'src', 'js');
global.window = {};
global.getComputedStyle = () => ({ getPropertyValue: () => '' });
for (const f of ['groups.js', 'fragments.js', 'compounds.js', 'massspec.js', 'evidence.js']) {
  eval.call(global, fs.readFileSync(path.join(src, f), 'utf8'));
}

const out = [];
const w = s => out.push(s == null ? '' : s);
const SRC = { ir: 'IR package', ms: 'mass spec package', new: '**new — spot-check**' };
const THEME_NAMES = {
  alcohol: 'Alcohols and ethers', carbonyl: 'Carbonyls', acid: 'Acids and acid derivatives',
  nitrogen: 'Nitrogen compounds', hydrocarbon: 'Hydrocarbons', halide: 'Halides'
};

function neutralOf(c, p) {
  const spec = { compound: c };
  return MS.neutralOf(spec, p) || '—';
}

w('# Answer key — IR and Mass Spectrometry: Two Spectra, One Compound');
w();
w('Generated by `node tools/answer-key.js > ANSWER_KEY.md`. Do not edit by hand — edit');
w('`src/js/compounds.js` and regenerate.');
w();
w('Every compound carries both an IR band table and a mass spectrum peak table. The');
w('**Source** column says where each came from: carried over from the IR or the mass spec');
w('package, or **new** — written for this package from standard literature values, rounded');
w('and idealised the same way. The new ones are the ones worth checking against a');
w('reference spectrum (the NIST Chemistry WebBook has both kinds for every compound here).');
w();

/* ------------------------------------------------------------------ summary */
w('## At a glance');
w();
w('| Compound | Formula | M⁺ | Cl/Br | N | What the IR says | Base peak | Answer at | IR source | MS source |');
w('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
Object.keys(THEME_NAMES).forEach(t => {
  COMPOUNDS.filter(c => c.theme === t).forEach(c => {
    const cf = Evidence.caseFile(c);
    w('| ' + [
      c.name + ' `' + c.id + '`', c.formula,
      cf.mass === 'none' ? '*none readable*' : cf.mass,
      cf.halogen === 'unknown' ? '—' : cf.halogen === 'none' ? 'no' : cf.halogen,
      cf.nitrogen === 'unknown' ? '—' : cf.nitrogen === 'odd' ? 'yes' : 'no',
      Evidence.IR_CLASSES[cf.irclass].label,
      cf.base,
      Evidence.readableM(c) ? 'Levels 1–4' : 'Levels 3–4',
      SRC[c.source.ir], SRC[c.source.ms]
    ].join(' | ') + ' |');
  });
});
w();
w('"Answer at" is where the compound can be the one to identify. Every compound can be');
w('offered as a wrong option at any level. A compound with no readable molecular ion cannot');
w('be an answer at Levels 1–2, because every mass spectrum label is a loss from M⁺.');
w();

/* ---------------------------------------------------------------- the pairs */
w('## Where one spectrum cannot decide');
w();
w('These are the sets the wrong options are drawn from first.');
w();
w('**IR twins** — the same scored IR bands. Only the mass spectrum separates them.');
w();
const irTwins = {};
COMPOUNDS.forEach(c => { const k = Evidence.scoredGroups(c).join('+'); (irTwins[k] = irTwins[k] || []).push(c); });
Object.entries(irTwins).filter(([, g]) => g.length > 1).forEach(([k, g]) => {
  w('- ' + g.map(c => c.name + ' (' + (Evidence.readableM(c) || 'no M⁺') + ', base ' + Evidence.basePeak(c) + ')').join(' · ') +
    ' — IR: ' + k.split('+').map(x => GROUPS[x].label).join(', '));
});
w();
w('**Mass twins** — the same readable molecular ion. The IR separates them in one look.');
w();
const massTwins = {};
COMPOUNDS.forEach(c => { const M = Evidence.readableM(c); if (M) (massTwins[M] = massTwins[M] || []).push(c); });
Object.entries(massTwins).filter(([, g]) => g.length > 1).forEach(([m, g]) => {
  w('- M = ' + m + ': ' + g.map(c => c.name + ' (' + Evidence.IR_CLASSES[Evidence.irClass(c)].label.toLowerCase() + ')').join(' · '));
});
w();

/* ------------------------------------------------------------ per compound */
w('## Compound by compound');
w();
Object.keys(THEME_NAMES).forEach(t => {
  w('### ' + THEME_NAMES[t]);
  w();
  COMPOUNDS.filter(c => c.theme === t).forEach(c => {
    const cf = Evidence.caseFile(c);
    const M = Evidence.massOf(c);
    w('#### ' + c.name + ' — ' + c.formula + ', M = ' + M + ' (`' + c.id + '`)');
    w();
    w('*' + c.cls + '.* Case file: ' + [
      cf.massText, Evidence.HALOGEN_TEXT[cf.halogen], Evidence.NITROGEN_TEXT[cf.nitrogen],
      Evidence.IR_CLASSES[cf.irclass].label, 'base peak ' + cf.baseText
    ].join(' · ') + '.');
    w();
    w('**IR** (' + SRC[c.source.ir] + ') — scored bands:');
    w();
    w('| Group | Centre (cm⁻¹) | Accepted window | Textbook range |');
    w('| --- | --- | --- | --- |');
    c.bands.filter(b => b.t).sort((a, b) => b.c - a.c).forEach(b => {
      w('| ' + GROUPS[b.g].label + ' | ' + b.c + ' | ' + b.tol.join('–') + ' | ' + GROUPS[b.g].range + ' |');
    });
    const fp = c.bands.filter(b => !b.t && b.g).map(b => GROUPS[b.g].label + ' ' + b.c);
    if (fp.length) { w(); w('Drawn, never scored: ' + fp.join(', ') + '.'); }
    Object.entries(c.hidden || {}).forEach(([g, why]) => {
      w(); w('Present but not scored: ' + GROUPS[g].label + ' — ' + why + '.');
    });
    w();
    w('**Mass spectrum** (' + SRC[c.source.ms] + '):');
    w();
    w('| m/z | % | Role | Loss | Neutral lost | Notes |');
    w('| --- | --- | --- | --- | --- | --- |');
    const readable = Evidence.readableM(c);
    c.peaks.slice().sort((a, b) => b.mz - a.mz).forEach(p => {
      const role = p.role === 'key' ? (readable ? '**scored**' : 'key (not scored: no M⁺)') :
                   p.role === 'mplus' ? '**M⁺ (scored)**' : p.role === 'mcl' ? 'rearrangement' : p.role;
      const loss = p.role === 'mplus' ? '—' : 'M − ' + (M - p.mz);
      const note = (p.why || p.note || (p.ion ? IONS[p.ion].label : '')).replace(/\|/g, '/');
      w('| ' + p.mz + ' | ' + p.ab + ' | ' + role + ' | ' + loss + ' | ' +
        (p.ion ? neutralOf(c, p) : '—') + ' | ' + note + ' |');
    });
    if (c.isotopeTarget && readable) {
      const mp = c.peaks.find(p => p.role === 'mplus');
      const hal = Evidence.halogen(c);
      const iso = mp.ab * (hal === 'Br' ? 0.973 : 0.32);
      w();
      w('M+2 at m/z ' + (M + 2) + ' is computed from the formula, about ' + iso.toFixed(0) + '% — ' +
        (iso >= 5 ? 'scored.' : 'under the reading line, so drawn but not scored.'));
    }
    w();
    const rivals = Evidence.pickDecoys(c, 3, MS.rng(7));
    w('**Typical wrong options:**');
    w();
    rivals.forEach(d => {
      const v = Evidence.whyNot(c, d);
      w('- *' + d.name + '* — ' + [v.ir ? 'IR: ' + v.ir : 'IR: no help.',
                                   v.ms ? 'MS: ' + v.ms : 'MS: no help.'].join(' '));
    });
    w();
  });
});

/* ------------------------------------------------------------ vocabulary */
w('## Mass spectrum losses offered as labels');
w();
w('| Loss | Neutral | Note |');
w('| --- | --- | --- |');
Object.keys(LOSSES).map(Number).sort((a, b) => a - b).forEach(n => {
  const L = LOSSES[n];
  w('| M − ' + n + ' | ' + L.neutral + (L.also ? ' or ' + L.also : '') + ' | ' + L.hint.replace(/\|/g, '/') + ' |');
});
w();

process.stdout.write(out.join('\n') + '\n');
