#!/usr/bin/env node
/* answer-key.js: writes ANSWER_KEY.md from the item bank.
 *
 *   node tools/answer-key.js > ANSWER_KEY.md
 */

'use strict';

var fs = require('fs');
var path = require('path');
var vm = require('vm');

var SRC = path.join(__dirname, '..', 'src');
var ctx = vm.createContext({});
['data.js', 'atom.js', 'checks.js', 'plan.js', 'items.js'].forEach(function (f) {
  vm.runInContext(fs.readFileSync(path.join(SRC, 'js', f), 'utf8'), ctx, { filename: f });
});
var DATA = vm.runInContext('DATA', ctx);
var Atom = vm.runInContext('Atom', ctx);
var Checks = vm.runInContext('Checks', ctx);
var Items = vm.runInContext('Items', ctx);

var O = Atom.ordinal, out = [];
function line(s) { out.push(s == null ? '' : s); }

var SOURCE = { part5: 'Part 5, as printed', 'part2+ref': '1st from Part 2, the rest reference values' };

function ieCells(sym, n) {
  var ie = DATA.IE[sym].ie.slice(0, n || undefined), o = Atom.outer(sym);
  return ie.map(function (v, i) { return i === o ? '**' + v + '**' : String(v); }).join(', ');
}

line('# Answer Key: Successive Ionization Energies');
line();
line('Generated by `tools/answer-key.js`. Do not edit by hand; edit `src/js/data.js` or `src/js/checks.js` and regenerate.');
line();
line('Every answer follows the two-step rule from the packet. **Step 1:** count the OCCUPIED energy levels; if they differ, that settles it. **Step 2:** only if they are the same do the protons decide. Inside one element the protons never change, so a step up inside one occupied level is small (the particle is more positive each time) and the move to a lower occupied level is the huge jump.');
line();

/* ------------------------------------------------------------------ data */

line('## The data');
line();
line('Values in kJ/mol. The first value past the huge jump is in **bold**.');
line();
line('| Element | Row | Group | Electrons in outer level | Ionization energies | Jump | Source |');
line('| --- | :-: | :-: | :-: | --- | --- | --- |');
Object.keys(DATA.IE).sort(function (a, b) { return DATA.z(a) - DATA.z(b); }).forEach(function (sym) {
  var ie = DATA.IE[sym].ie, o = Atom.outer(sym);
  line('| ' + Atom.cap(DATA.name(sym)) + ' (' + sym + ') | ' + Atom.row(sym) + ' | ' + Atom.group(sym) + ' | ' + o +
       ' | ' + ieCells(sym) + ' | after the ' + O(o) + ', ' + Atom.times(ie[o - 1], ie[o]) + ' | ' +
       SOURCE[DATA.IE[sym].src] + ' |');
});
line();
line('Part 2 and Part 5 of the packet disagree by 1 or 2 kJ/mol for four elements: Part 2 lists Na 495, Mg 737, Al 576 and Be 898, while Part 5 uses 496, 738, 578 and 899. This activity uses the Part 5 values, since Part 5 is the successive ionization energy page.');
line();

/* ---------------------------------------------------------------- Part 1 */

line('## Part 1: Strip the atom');
line();
line('One of these per run. Students predict each ionization energy before it is revealed, and answer why at the first small step and at the jump.');
line();
DATA.STRIP.forEach(function (sym) {
  var ie = DATA.IE[sym].ie, o = Atom.outer(sym);
  line('### ' + Atom.cap(DATA.name(sym)) + ', ' + Atom.configText(sym, 0));
  line();
  line('| Electron | Pulled off | Occupied levels in that particle | Comes from | kJ/mol | Prediction |');
  line('| :-: | --- | :-: | :-: | :-: | --- |');
  for (var k = 1; k <= Items.STRIP_SHOWN; k++) {
    var jump = k > 1 && Atom.levelOf(sym, k) < Atom.levelOf(sym, k - 1);
    line('| ' + O(k) + ' | ' + Atom.ion(sym, k - 1) + ' (' + Atom.configText(sym, k - 1) + ') | ' +
         Atom.occupied(sym, k - 1) + ' | level ' + Atom.levelOf(sym, k) + ' | ' + ie[k - 1] + ' | ' +
         (k === 1 ? 'n/a' : jump ? 'huge jump' : 'small step up') + ' |');
  }
  line();
  line('Electrons in the outer level: **' + o + '**. Ion formed: **' + Atom.ion(sym, o) + '**.');
  line();
});

/* ---------------------------------------------------------------- Part 2 */

line('## Part 2: Mystery elements');
line();
line('Each run shows two of these, one as a table and one as a bar graph: one from groups 1 and 2, one from groups 13 to 15, never the Part 1 element.');
line();
line('| Row | Ionization energies | Huge jump | Outer electrons | Group | Element | Configuration | Ion |');
line('| :-: | --- | --- | :-: | :-: | --- | --- | --- |');
DATA.FULL.forEach(function (sym) {
  var ie = DATA.IE[sym].ie, o = Atom.outer(sym);
  line('| ' + Atom.row(sym) + ' | ' + ieCells(sym) + ' | ' + O(o) + ' to ' + O(o + 1) + ', ' + Atom.times(ie[o - 1], ie[o]) +
       ' | ' + o + ' | ' + Atom.group(sym) + ' | ' + DATA.name(sym) + ' (' + sym + ') | ' + Atom.configText(sym, 0) +
       ' | ' + (DATA.METALS.indexOf(sym) >= 0 ? Atom.ion(sym, o) : 'not asked') + ' |');
});
line();
line('Only metals are named as ions. Boron, carbon, silicon and phosphorus do not form the positive ion their jump points to, so the activity never says they do.');
line();

line('### The jump is not in the data');
line();
line('One per run. Only the first ' + Atom.word(DATA.HIDDEN_SHOWN) + ' values are shown. Answers: the jump is **not in this data**; there are **at least ' +
     DATA.HIDDEN_SHOWN + '** electrons in the outer level; the **' + O(DATA.HIDDEN_SHOWN + 1) +
     ' and later** ionization energies would settle it. Then the full data is shown and students give the group.');
line();
line('| Row | Shown | Full data | Group | Element |');
line('| :-: | --- | --- | :-: | --- |');
DATA.HIDDEN.forEach(function (sym) {
  line('| ' + Atom.row(sym) + ' | ' + DATA.IE[sym].ie.slice(0, DATA.HIDDEN_SHOWN).join(', ') + ' | ' + ieCells(sym) +
       ' | ' + Atom.group(sym) + ' | ' + DATA.name(sym) + ' (' + sym + ') |');
});
line();

line('### Head to head');
line();
line('One per run. In every pair the first element has already emptied its outer level, so Step 1 decides and the extra proton in the second element never gets a vote.');
line();
line('| Question | Particles | Occupied levels | Step | Larger | Values (kJ/mol) |');
line('| --- | --- | :-: | :-: | --- | --- |');
DATA.PAIRS.forEach(function (p) {
  var a = p[0], b = p[1], k = p[2];
  line('| Larger ' + O(k) + ' ionization energy, ' + DATA.name(a) + ' or ' + DATA.name(b) + '? | ' +
       Atom.ion(a, k - 1) + ' and ' + Atom.ion(b, k - 1) + ' | ' + Atom.occupied(a, k - 1) + ' and ' +
       Atom.occupied(b, k - 1) + ' | 1 | ' + DATA.name(a) + ' | ' + DATA.IE[a].ie[k - 1] + ' against ' +
       DATA.IE[b].ie[k - 1] + ' |');
});
line();

/* ---------------------------------------------------------------- checks */

var TAG_NAMES = {
  eq: 'What the kth ionization energy removes',
  small: 'Why each one costs a little more',
  occ: 'Occupied energy levels after electrons come off',
  cause: 'Explaining the jump with occupied levels, not size or wanting',
  ion: 'Reading the ion and the group from the data'
};

line('## Check questions');
line();
line('One check sits in the middle of Part 2 and three make up the checkpoint, each from a different tag. A missed check brings back a different question with the same tag (at most two extra per part).');
line();
Checks.TAGS.forEach(function (t) {
  line('### ' + TAG_NAMES[t] + ' (`' + t + '`)');
  line();
  Checks.byTag(t).forEach(function (q) {
    line('**' + q.id + '.** ' + q.q);
    line();
    line('- Answer: **' + q.a[0] + '**');
    line('- Other options: ' + q.a.slice(1).join('; '));
    line('- Explanation shown: ' + q.why);
    line();
  });
});

process.stdout.write(out.join('\n'));
